### PR TITLE
Adding French translation

### LINKED ISSUE #10: French translation
@cmaumet and @CPernet are working on the French translation of the ultimate consent form. It's available here: https://docs.google.com/document/d/10yacu6_ud9nrLjyiAWRuLgGMkYaCxXX6E1XfAsPCbVM/edit and we should merge it  this repository when it is done into.

### PR DESCRIPTION
**Pull request by chrisfilo**
courtesy of @CPernet @cmaumet and Clara Moreau

edit by @yarikoptic Closes #10

### CODE REVIEW

**Comment by yarikoptic** [comment]
@jbpoline , would you mind giving an informed review and ack/nack for the PR? ;)

**Comment by CPernet** [comment]
hey, been on-line for a while -  I did it 1st,  @cmaumet and Clara then changed/updated/corrected + a bunch of people; should be fine now :-)

**Comment by yarikoptic** [comment]
ok, let's just do it and fixup later happen any defect is found

**Comment by chrisfilo** [comment]
It does not show up on RTD. Something went wrong with the build?

**Comment by CPernet** [comment]
any defect?? mmh thx pal :D

**Comment by yarikoptic** [comment]
apparently integration with github wasn't setup. fixed now
BTW @chrisfilo - you are the owner on RTD for this thing as well, so have all the super powers

**Comment by vsoch** [comment]
+1 that @chrisfilo has superpowers.

**Comment by yarikoptic** [comment]
haha -- should I add you @vsoch to the Vanessasaurus translators team on https://github.com/orgs/datalad/teams/translators/teams ? ;)

**Comment by vsoch** [comment]
You definitely could, but it's a very rarely spoken and challenging language "#rawr"

**Comment by yarikoptic** [comment]
> You definitely could, but it's a very rarely spoken and challenging language "#rawr"

done! ;-)

**Pull request merged**
