### PR TITLE
Chinese Version

### PR DESCRIPTION
**Pull request by hcp4715**
both versions were translated and proofread.

### CODE REVIEW

**Comment by hcp4715** [comment]
Maybe @feilong can compare these two translations and combine them together.
And I guess it'd better make the Chinese version public soon, just in case that other enthusiastic Chinese researchers translate another version ;-)

**Comment by feilong** [comment]
Both versions are of great quality and are good to use in my opinion @yarikoptic @hcp4715 .

I prefer some expressions in PR22.  For example, "只有一个代码可以将二者联系起来" (PR22) is clearer than "两者仅通过代码来识别" (PR25); "是否让我们使用及分享你的数据将完全由你自愿决定" (PR22) sounds slightly better than "允许我们使用并且分享您的数据是自愿行为" (PR25) because it explicitly states that it's the participant's decision (but I'll probably change "你" to "您" to be consistent).

I'll leave the final decision to the authors.

**Comment by hcp4715** [comment]
Hi, @feilong . 
Thanks for quick response!
Your suggestions are brilliant, You can change it directly.

**Comment by yarikoptic** [comment]
Dear @feilong, could you please implement that change and also acknowledge the author of #22 and your own editing contribution?  I've invited you to become collaborator on this repository so you should be able to push to this PR (to the patch-1 branch of hcp4715's clone).  Thanks in advance!

**Pull request merged**
