### PR TITLE
Added german translation of the ultimate consent form

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by yarikoptic** [comment]
@mih could you please help to review? ;)

**Comment by vsoch** [comment]
:scream:

**Comment by mih** [comment]
I can certify that this is German, but only the words and the grammar. It sounds waayyyy to friendly -- not one exclamation mark, no imperatives -- as a German, this leaves me confused and uncertain. Please give precise instructions on how to proceed!

**Comment by vsoch** [comment]
I know who to ask! https://www.youtube.com/watch?v=Qb1_UjIPCTE

**Comment by mih** [comment]
That's the spirit! And great idea to bring some motherly affection into the
mix!

**Comment by chrisfilo** [comment]
Could someone merge this? Giving a talk in Berlin next week and I would like to make this translation more accessible. @yarikoptic

**Comment by yarikoptic** [comment]
@mih I will merge it as is since you certified that it is a legit German. If exclamation marks are needed to make it more official to the German eye, please contribute - I wouldn't be able to. Cheers

**Comment by chrisfilo** [comment]
@yarikoptic - the PR has been merged, but I cannot see the translation online at http://open-brain-consent.readthedocs.io/en/latest/ultimate.html. Is there a problem with RTD?

**Comment by yarikoptic** [comment]
yeah, apparently wasn't yet fully setup... triggered rebuild so German translation is online. enabled the hook now but still not sure...  If you like -- what is your login at RTD, i will add you

**Comment by chrisfilo** [comment]
filo

**Comment by yarikoptic** [comment]
again my reply via email didn't get posted -- added you

**Pull request merged**
